### PR TITLE
Upgrade to the COLMAP head. Use FetchContent for PoseLib and COLMAP

### PR DESCRIPTION
**Pull request by B1ueber2y**
* Use FetchContent for PoseLib and COLMAP. Now there is no need to install PoseLib and COLMAP beforehand. And if it is already installed one can switch the macro here: https://github.com/cvg/limap/blob/features/colmap_head/CMakeLists.txt#L26-L27
* Adapt limap to the newest version of COLMAP and pin the commit id https://github.com/cvg/limap/blob/features/colmap_head/cmake/FindDependencies.cmake#L59
* Use ceres, FreeImage and Boost from system rather than from COLMAP
* Update README. Remove COLMAP and PoseLib and copy the COLMAP dependency into README. 
* Upgrade DeepLSD

This works in my test after installation. More tests are appreciated.
```
python -c "import limap; print(limap.__version__)"
```

Will add the installation test into CI for the next step (in a separate PR after this is merged).

### CODE REVIEW

**Comment by rpautrat** [comment]
With which Python version did you build it in your tests? The compilation of PoseLib is failing for me with Python 3.10:
```
    [ 35%] Building CXX object _deps/poselib-build/PoseLib/CMakeFiles/PoseLib.dir/robust/estimators/relative_pose.cc.o
    [ 35%] Building CXX object _deps/poselib-build/PoseLib/CMakeFiles/PoseLib.dir/robust/estimators/hybrid_pose.cc.o
    [ 36%] Building CXX object _deps/poselib-build/PoseLib/CMakeFiles/PoseLib.dir/robust/estimators/homography.cc.o
    [ 36%] Linking CXX static library libcolmap_poisson_recon.a
    [ 36%] Built target colmap_poisson_recon
    [ 36%] Linking CXX static library libPoseLib.a
    [ 36%] Built target PoseLib
    gmake: *** [Makefile:136: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/pautratrmi/Documents/external/test/limap/setup.py", line 68, in <module>
        setup(
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
        return distutils.core.setup(**attrs)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
        return run_commands(dist)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
        dist.run_commands()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
        self.run_command(cmd)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
        super().run_command(command)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/command/develop.py", line 35, in run
        self.install_for_development()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/command/develop.py", line 112, in install_for_development
        self.run_command('build_ext')
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/dist.py", line 995, in run_command
        super().run_command(command)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
        cmd_obj.run()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 99, in run
        _build_ext.run(self)
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
        self._build_extensions_serial()
      File "/home/pautratrmi/env_limap/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/pautratrmi/Documents/external/test/limap/setup.py", line 59, in build_extension
        subprocess.check_call(
      File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--parallel 8']' returned non-zero exit status 2.
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /home/pautratrmi/env_limap/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize

    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)

    __file__ = %r
    sys.argv[0] = __file__

    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"

    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/home/pautratrmi/Documents/external/test/limap/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /home/pautratrmi/Documents/external/test/limap/
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Upgrading setuptools to the latest version doesn't help.

**Comment by B1ueber2y** [comment]
The previous issue was fixed here (due to copy construction behavior in pybind11): https://github.com/cvg/limap/pull/98/commits/6e14755241f2b7822a5844b1f5904bf0457e9350. Now both quickstarts work for me. 

Will add the quickstart tests to CI test in the future PR.

**Comment by B1ueber2y** [comment]
One thing to mention is that the parallelization for fitting 3D lines in the fitnmerge pipeline is currently broken. However, it is the bottleneck so we could live with it: https://github.com/cvg/limap/pull/98/commits/2957ebf2d2d340a7a3e09054e8c00ee9f7c0d9f9. Will look into it in later days.

**Review by rpautrat — APPROVED** [review]

**Comment by B1ueber2y** [comment]
> One thing to mention is that the parallelization for fitting 3D lines in the fitnmerge pipeline is currently broken. However, it is not the bottleneck so we could live with it: [2957ebf](https://github.com/cvg/limap/commit/2957ebf2d2d340a7a3e09054e8c00ee9f7c0d9f9). Will look into it in later days.

This is resolved by https://github.com/cvg/limap/pull/105

**Pull request merged**
